[project]
name = "nutritiontracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Debojyoti-55", email = "debojyoti1835@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate",
    "astrapy>=2.3.1",
    "db>=0.1.1",
    "einops",
    "langchain>=1.4.0",
    "langchain-astradb>=1.0.0",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.2",
    "openai>=3.10.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pillow",
    "pymongo>=4.18.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
    "timm",
    "torch",
    "transformers",
]



[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
